# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basics', '0002_auto_20160201_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.NullBooleanField()),
                ('mod_time', models.DateTimeField(verbose_name='time voted')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='contributer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_index',
        ),
        migrations.AddField(
            model_name='question',
            name='makefile',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basics.Answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basics.Choice'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basics.Comment'),
        ),
        migrations.AddField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.Answer'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
